{
 "title": "ACE / Policy / Cluster Violations",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "constraint",
    "label": "constraint",
    "query": {
     "query": "label_values(policy_appscode_com_cluster_violation_occurrence_by_constraint_type, constraint) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Policy violation occurrence total",
   "type": "graph",
   "description": "Total number of Gatekeeper policy violations occurred in cluster scope",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (policy_appscode_com_cluster_violation_occurrence_total)"
    }
   ]
  },
  {
   "title": "Cluster Policy violation occurrence  by Constraint type",
   "type": "graph",
   "description": "Total number of policy violations occurred in cluster scope by constraint type",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (constraint) (policy_appscode_com_cluster_violation_occurrence_by_constraint_type{constraint=\"$constraint\"})",
     "legendFormat": "{{ constraint }}"
    }
   ]
  }
 ]
}
{
 "title": "ACE / Policy / Namespace Violations",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "ns",
    "label": "ns",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "constraint",
    "label": "constraint",
    "query": {
     "query": "label_values(policy_appscode_com_cluster_violation_occurrence_by_constraint_type, constraint) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace Policy violation Occurrence total",
   "type": "graph",
   "description": "Total number of Gatekeeper policy violations occurred in namespace scope",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "policy_appscode_com_namespace_violation_occurrence_total{namespace=\"$ns\"}",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Namespace Policy Violation occurrence  by Constraint type",
   "type": "graph",
   "description": "Total number of policy violations occurred in namespace scope by constraint type",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "policy_appscode_com_namespace_violation_occurrence_by_constraint_type{namespace=\"$ns\",constraint=\"$constraint\"}",
     "legendFormat": "ns={{ namespace }}  , constraint= {{ constraint }}"
    }
   ]
  }
 ]
}