{
 "title": "Redis Operator / Cluster Dashboard",
 "tags": [ "redis" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(redis_up, service)"
    }
   },
   { "name": "env", "label": "Environment", "query": { "query": "label_values(up,env)" } }
  ]
 },
 "panels": [
  {
   "title": "Redis Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_up{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Redis Connected Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Redis Connection Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((redis_config_maxclients{env=~\"$env\"} - redis_connected_clients{env=~\"$env\"}) / redis_config_maxclients{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Redis Commands Executed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(redis_commands_processed_total{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Slots Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_cluster_slots_fail{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Redis Role",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_instance_info{namespace=~\"$namespace\",service=~\"$service\",role=\"master\",env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Redis Last Changes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(redis_rdb_changes_since_last_save{env=~\"$env\"})"
    }
   ]
  },
  {
   "title": "Redis Executed Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, increase(redis_commands_total{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"} [$__rate_interval]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Redis Command Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(redis_commands_duration_seconds_total{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"}[1m])) by (cmd)\n  /\navg(irate(redis_commands_total{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"}[1m])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Redis Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_db_keys{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Redis Input Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Output Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_output_bytes_total{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_master_repl_offset{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"} - redis_slave_repl_offset{namespace=~\"$namespace\",service=~\"$service\",env=~\"$env\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Cluster Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(redis_cluster_slots_ok{env=~\"$env\"})",
     "legendFormat": "Ok"
    },
    {
     "expr": "sum(redis_cluster_slots_fail{env=~\"$env\"})",
     "legendFormat": "fail"
    }
   ]
  }
 ]
}
{
 "title": "Traefik",
 "description": "Traefik metrics overview",
 "tags": [
  "Traefik",
  "Ingress"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(traefik_config_reloads_total, namespace)"
    }
   },
   { "name": "percentiles", "label": "Percentiles", "query": "95,99" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{namespace=\"$namespace\",condition=\"true\",pod=~\"traefik.*\"})"
    }
   ]
  },
  {
   "title": "Per instance latency $percentiles th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{namespace=\"$namespace\",code=~\"2..\"}[5m])) by (instance, le))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Entrypoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{namespace=\"$namespace\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Apdex score (over 5 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{namespace=\"$namespace\",le=\"0.1\",code=\"200\"}[5m])) by (job) + sum(rate(traefik_entrypoint_request_duration_seconds_bucket{namespace=\"$namespace\",le=\"0.3\",code=\"200\"}[5m])) by (job)) / 2 / sum(rate(traefik_entrypoint_request_duration_seconds_count{namespace=\"$namespace\",code=\"200\"}[5m])) by (job)",
     "legendFormat": "Code 200"
    }
   ]
  },
  {
   "title": "Requests/min per entrypoint",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{namespace=\"$namespace\"}[1m])) by (entrypoint)",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{namespace=\"$namespace\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Apdex score (over 5 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(traefik_service_request_duration_seconds_bucket{namespace=\"$namespace\",le=\"0.1\",code=\"200\"}[5m])) by (job) + sum(rate(traefik_service_request_duration_seconds_bucket{namespace=\"$namespace\",le=\"0.3\",code=\"200\"}[5m])) by (job)) / 2 / sum(rate(traefik_service_request_duration_seconds_count{namespace=\"$namespace\",code=\"200\"}[5m])) by (job)",
     "legendFormat": "200"
    }
   ]
  },
  {
   "title": "Requests/min per service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{namespace=\"$namespace\"}[1m])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "HTTP Codes stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status code 2xx over 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{namespace=\"$namespace\",code=~\"2..\"}[5m])) by (method, code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Status code 4xx over 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{namespace=\"$namespace\",code=~\"4.*\"}[5m])) by (method, code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Status code 3xx over 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{namespace=\"$namespace\",code!~\"2..|4..|5..\"}[5m])) by (method, code)",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "Status code 5xx over 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{namespace=\"$namespace\",code=~\"5..\"}[5m])) by (method, code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Pods resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traefik memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"traefik\"})",
     "legendFormat": "Memory used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",container=\"traefik\"})",
     "legendFormat": "Requested memory"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"traefik\"})",
     "legendFormat": "Limit memory usage"
    }
   ]
  },
  {
   "title": "Traefik CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"traefik\"}[2m]))",
     "legendFormat": "Cpu used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",container=\"traefik\"})",
     "legendFormat": "Requested cpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",container=\"traefik\"})",
     "legendFormat": "Limit cpu usage"
    }
   ]
  }
 ]
}
{
 "title": "Cert Manager",
 "tags": [ "cert-manager" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Certificates Ready",
   "type": "stat",
   "description": "The number of certificates in the ready state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition) (certmanager_certificate_ready_status)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Soonest Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(certmanager_certificate_expiration_timestamp_seconds > 0) - time()"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "table",
   "description": "Status of the certificates. Values are True, False or Unknown.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(avg by (name, namespace, condition, exported_namespace) (certmanager_certificate_ready_status == 1), \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    },
    {
     "expr": "label_join(avg by (name, namespace, exported_namespace) (certmanager_certificate_expiration_timestamp_seconds) * 1000, \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    }
   ]
  },
  {
   "title": "Controller Sync Requests/sec",
   "type": "graph",
   "description": "The rate of controller sync requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (controller) (\n  rate(certmanager_controller_sync_call_count[$__rate_interval])\n)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "ACME HTTP Requests/sec",
   "type": "graph",
   "description": "Rate of requests to ACME provider.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path, status) (\n  rate(certmanager_http_acme_client_request_count[$__rate_interval])\n)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "ACME HTTP Request avg duration",
   "type": "graph",
   "description": "Average duration of requests to ACME provider. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path, status) (rate(certmanager_http_acme_client_request_duration_seconds_sum[$__rate_interval]))\n/\nsum by (method, path, status) (rate(certmanager_http_acme_client_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU Usage and limits, as percent of a vCPU core. ",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (rate(container_cpu_usage_seconds_total{container=\"cert-manager\"}[$__rate_interval]))",
     "legendFormat": "CPU {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "description": "Percent of the time that the CPU is being throttled. Higher is badderer. ",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (\n  rate(container_cpu_cfs_throttled_periods_total{container=\"cert-manager\"}[$__rate_interval])\n  /\n  rate(container_cpu_cfs_periods_total{container=\"cert-manager\"}[$__rate_interval])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory utilisation and limits.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (container_memory_usage_bytes{container=\"cert-manager\"})",
     "legendFormat": "Memory {{pod}}"
    },
    {
     "expr": "avg by (pod) (kube_pod_container_resource_limits_memory_bytes{container=\"cert-manager\"})",
     "legendFormat": "Limit {{pod}}"
    },
    {
     "expr": "avg by (pod) (kube_pod_container_resource_requests_memory_bytes{container=\"cert-manager\"})",
     "legendFormat": "Request {{pod}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "description": "Network ingress/egress.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(\n  sum without (interface) (\n    rate(container_network_receive_bytes_total{namespace=\"cert-manager\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "receive"
    },
    {
     "expr": "avg(\n  sum without (interface) (\n    rate(container_network_transmit_bytes_total{namespace=\"cert-manager\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}
{
 "title": "Loki / Logs Overview",
 "description": "Logs collected from Kubernetes, stored in Loki",
 "tags": [
  "logs",
  "loki"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "stream", "query": "label_values(stream)" },
   { "name": "container", "query": "label_values(container)" }
  ]
 },
 "panels": [
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", stream=~\"$stream\", container =~\"$container\"} |= \"$query\" [$__interval]))",
     "legendFormat": "Log count"
    }
   ]
  },
  {
   "type": "logs",
   "description": "Logs from services running in Kubernetes",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", stream=~\"$stream\", container =~\"$container\"} |= \"$query\""
    }
   ]
  }
 ]
}
{
 "title": "Loki / Loki & Promtail Stats",
 "description": "Loki and Promtail metrics",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Loki's stored chunk entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(loki_ingester_chunk_entries_count[5m])"
    }
   ]
  },
  {
   "title": "Average batch appends sent to ingesters (Loki)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (loki_distributor_ingester_appends_total[1m])"
    }
   ]
  },
  {
   "title": "Number of bytes total by promtail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (promtail_file_bytes_total{instance=~\".*\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Number of bytes encoded and ready to send by Promtail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (promtail_encoded_bytes_total{pod=~'.*'}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Loki / Global Metrics",
 "description": "Loki 2.0 metrics",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Message Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(loki_log_messages_total)" }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(loki_store_series_total)" }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total)"
    }
   ]
  },
  {
   "title": "Panic ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_panic_total" }
   ]
  },
  {
   "title": "API Request Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[5m])) by (le,route))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received Lines / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total[5m]))",
     "legendFormat": "distributor / {{ tenant}}"
    }
   ]
  },
  {
   "title": "Distributor  Received bytes / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[5m])) by (tenant)",
     "legendFormat": "distributor / {{tenant}}"
    }
   ]
  },
  {
   "title": "Batch Appends Sent to Ingesters / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_appends_total[5m])",
     "legendFormat": "successed"
    },
    {
     "expr": "loki_distributor_ingester_append_failures_total",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Store Series / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(loki_store_series_total[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks / Chunk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket[5m])) by (le))",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket[5m])) by (le))",
     "legendFormat": "chunk size"
    }
   ]
  },
  {
   "title": "Chunk Age",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket[5m])) by (le))",
     "legendFormat": "ages"
    }
   ]
  },
  {
   "title": "Chunk Compression Ratios",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket[5m])) by (le))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Chunk Encode Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "durations."
    }
   ]
  },
  {
   "title": "Lines / Chunk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket[5m])) by (le))",
     "legendFormat": "lines"
    }
   ]
  },
  {
   "title": "Chunk Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total[5m]))",
     "legendFormat": "flush / {{ reason }}"
    },
    {
     "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
     "legendFormat": "stored"
    },
    {}
   ]
  },
  {
   "title": "Chunks in Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "loki_ingester_memory_chunks", "legendFormat": "chunks" }
   ]
  },
  {
   "title": "Chunks in Streams",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenan) (loki_ingester_memory_streams)",
     "legendFormat": "streams"
    }
   ]
  },
  {
   "title": "Strams Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_ingester_streams_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(loki_ingester_streams_removed_total[5m])",
     "legendFormat": "delete"
    }
   ]
  }
 ]
}
{
 "title": "Crowdsec / Overview",
 "tags": [ "crowdsec" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Crowdsec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"crowdsec.*\"})"
    }
   ]
  },
  {
   "title": "Acquisitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_filesource_hits_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    },
    {
     "expr": "sum(increase(cs_journalctlsource_hits_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    },
    {
     "expr": "sum(increase(cs_cloudwatch_stream_hits_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    },
    {
     "expr": "sum(increase(cs_syslogsource_hits_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Parsers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Buckets overflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Decisions Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cs_active_decisions)" }
   ]
  },
  {
   "title": "Alerts Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cs_alerts)" }
   ]
  },
  {
   "title": "Decisions by scenario",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(cs_active_decisions) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Decisions By Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(cs_active_decisions) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Parsers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Parsers ok",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_node_hits_ok_total[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Parsers nok",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_node_hits_ko_total[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Buckets created",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_created_total[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets overflow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_overflowed_total[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets Timeline",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(cs_buckets) by (name)", "legendFormat": "{{name}}" }
     ]
    }
   ]
  }
 ]
}