{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Virtual Users",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_check",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "check" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "$Measurement",
 "panels": [
  {
   "title": "$Measurement (mean)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM $Measurement WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (max)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM $Measurement WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (med)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"value\") FROM $Measurement WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (min)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"value\") FROM $Measurement WHERE $timeFilter and value > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (p90)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"value\", 90) FROM $Measurement WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (p95)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"value\", 95) FROM $Measurement WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "graph",
   "description": "Grouped by 1 sec intervals",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT max(\"value\") FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT percentile(\"value\", 95) FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "p90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT percentile(\"value\", 90) FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT min(\"value\") FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "heatmap",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT \"value\" FROM $Measurement WHERE $timeFilter and value > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": []
}
{
 "title": "Spring Boot 2.1 Statistics",
 "description": "Dashboard for Spring Boot2.1 Statistics(based on Spring Boot2 Statistic by micrometer-prometheus).",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  { "title": "JVM Statistics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  { "title": "HikariCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Connections Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 70 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "Tomcat Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Total Error Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 96 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tomcat_global_error_total{instance=\"$instance\", application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 96 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "active sessions"
    }
   ]
  },
  {
   "title": "Sent & Recieved Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(tomcat_global_sent_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "Sent Bytes"
    },
    {
     "expr": "irate(tomcat_global_received_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "Recieved Bytes"
    }
   ]
  },
  {
   "title": "Thread Config Max",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 100 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tomcat_threads_config_max{instance=\"$instance\", application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Current thread"
    },
    {
     "expr": "tomcat_threads_busy_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Current thread busy"
    }
   ]
  },
  { "title": "Logback Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "INFO logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"info\"}[5m])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 118 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 118 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Views / Global",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(kube_namespace_labels)", "legendFormat": "Namespaces" },
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase='Running'})",
     "legendFormat": "Running Pods"
    },
    { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
    { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
    { "expr": "sum(kube_ingress_info)", "legendFormat": "Ingresses" },
    { "expr": "sum(kube_deployment_labels)", "legendFormat": "Deployments" },
    { "expr": "sum(kube_statefulset_labels)", "legendFormat": "Statefulsets" },
    { "expr": "sum(kube_daemonset_labels)", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_persistentvolumeclaim_info)",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_hpa_labels)", "legendFormat": "Horizontal Pod Autoscalers" },
    { "expr": "sum(kube_configmap_info)", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info)", "legendFormat": "Secrets" },
    { "expr": "sum(kube_networkpolicy_labels)", "legendFormat": "Network Policies" },
    {
     "expr": "count(up{job=\"node-exporter\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_memory_bytes)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running'})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "CPU usage in %"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance)",
     "legendFormat": "{{ node}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Global Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "Total received bytes"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total[$__rate_interval]))",
     "legendFormat": "Total transmitted bytes"
    }
   ]
  },
  {
   "title": "Network Saturation - Packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total[$__rate_interval]))",
     "legendFormat": "Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total[$__rate_interval]))",
     "legendFormat": "Packets dropped (transmit)"
    }
   ]
  },
  {
   "title": "Network Received by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$__rate_interval])) by (namespace)",
     "legendFormat": "Received bytes in {{ namespace }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total[$__rate_interval])) by (namespace)",
     "legendFormat": "Transmitted bytes in {{ namespace }}"
    }
   ]
  },
  {
   "title": "Network Received by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$__rate_interval])) by (node)",
     "legendFormat": "Received bytes in {{ node }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total[$__rate_interval])) by (node)",
     "legendFormat": "Transmitted bytes in {{ node }}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Views / Namespaces",
 "description": "This is a modern 'Namespaces View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace(s) usage on total cluster CPU in %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[$__rate_interval])) / sum(machine_cpu_cores)"
    }
   ]
  },
  {
   "title": "Namespace(s) usage on total cluster RAM in %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\"}) / sum(machine_memory_bytes)"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{namespace=~\"$namespace\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_ingress_info{namespace=~\"$namespace\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{namespace=~\"$namespace\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{namespace=~\"$namespace\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{namespace=~\"$namespace\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Network Policies"
    }
   ]
  },
  {
   "title": "Namespace(s) CPU Usage in cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", unit=\"core\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", unit=\"core\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Cluster Total" }
   ]
  },
  {
   "title": "Namespace(s) RAM Usage in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", unit=\"byte\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_memory_bytes)", "legendFormat": "Cluster Total" }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Kubernetes Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Nb of pods by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"$namespace\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"})",
     "legendFormat": "Restarts Total"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})",
     "legendFormat": "Terminated"
    }
   ]
  },
  {
   "title": "Nb of containers by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replicas available by deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"}) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Replicas unavailable by deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"}) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  { "title": "Kubernetes Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Persistent Volumes - Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_inodes_used{namespace=~\"$namespace\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{namespace=~\"$namespace\"}) by (persistentvolumeclaim) * 100",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Views / Pods",
 "description": "This is a modern 'Pods View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Created by",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{ created_by_kind }}: {{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Running on",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Pod IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{ pod_ip }}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total pod CPU Requests usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}[$__rate_interval])) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", unit=\"core\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total pod CPU Limits usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}[$__rate_interval])) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", unit=\"core\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Total pod RAM Requests usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", unit=\"byte\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total pod RAM Limits usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", unit=\"byte\"}) ",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Resources by container",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", unit=\"core\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", unit=\"core\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", unit=\"byte\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", unit=\"byte\"}) by (container)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"POD\"}[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"POD\"}) by (container)"
    }
   ]
  },
  {
   "title": "CPU Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}[$__rate_interval])) by (container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", unit=\"core\"}) by (container)",
     "legendFormat": "{{ container }}  REQUESTS"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}[$__rate_interval])) by (container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", unit=\"core\"}) by (container)",
     "legendFormat": "{{ container }}  LIMITS"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", unit=\"byte\"}) by (container)",
     "legendFormat": "{{ container }} REQUESTS"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", unit=\"byte\"}) by (container)",
     "legendFormat": "{{ container }} LIMITS"
    }
   ]
  },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"POD\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  }
 ]
}